### PR TITLE
Cleanup environment from original deployment

### PR DESCRIPTION
**Pull request by mrocklin**
This had a number of examples and software packages that were more specific to atmospheric and oceanographic science than astronomy.

### CODE REVIEW

**Comment by mrocklin** [comment]
Anything special to do here @dsludwig , or do I just merge?

**Comment by dsludwig** [comment]
Just merging should do the trick.

**Comment by mrocklin** [comment]
This then goes to the live cluster or to a separate staging cluster?  (I notice that the branch name is staging)  Is there anything I should do locally to verify things?  (I'm currently running repo2docker)

**Comment by dsludwig** [comment]
It's going to the live cluster. It's deploying to the namespace 'staging', and if you merge to 'prod', it will deploy to that namespace. I haven't set it up to do anything sensible in that case, but we could point a different DNS name to it (`staging.astro.pangeo.io` & `astro.pangeo.io`).

All these namespaces would have to change if we move to a single cluster hosting many of these deployments.

**Pull request merged**
