### PR TITLE
Add astropy and sunpy to environment.yml

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by martindurant** [comment]
Should include intake-astro

**Comment by mrocklin** [comment]
Go for it.  Maybe also include an example notebook of its use?

**Comment by martindurant** [comment]
> Maybe also include an example notebook of its use?

Eventually!

**Comment by SimonKrughoff** [comment]
@martindurant are you going to add intake-astro, or are you expecting me to do it?

**Comment by mrocklin** [comment]
@SimonKrughoff my hope is that astronomers like yourself eventually take this over.  For example, you asked before about adding `cartopy` to the main pangeo deployment.  This is your opportunity to have your own system that you (or others in the future) can control.

**Comment by martindurant** [comment]
Yes, to second: I should have said "I think this should include intake-astro", for the reason that it bring parallel access to (non-compressed) arrays and tables, and allows the use of the Intake cataloging system.

However, it would be up to the maintainers of the repo, who should be primarily astronomers, that decide whether that's persuasive of not. I am, of course, happy to help out in making this repo and deployment a success for the astro community.

**Comment by SimonKrughoff** [comment]
OK.  Thanks both.  I'll merge.

**Comment by mrocklin** [comment]
You have no obligation to do any of this of course, but I thought it might be an interesting thing for you to experiment with.  I'm quite happy to spend time helping with anything on this topic or getting on the phone if you're interested @SimonKrughoff

**Comment by SimonKrughoff** [comment]
@mrocklin I'd be happy to chat too.  Let me formulate some questions and I'll ping you on the gitter.

**Comment by SimonKrughoff** [comment]
I'm merging this.  And will make another PR for additional packages.

**Pull request merged**
